### ISSUE TITLE
The function for 'lfe run' command is missing 'set_paths' call

### ISSUE THREAD

**Issue by prokopiy** [lfe-rebar3/rebar3_lfe#56]
How to run an LFE project?

My project [https://github.com/prokopiy/aira](https://github.com/prokopiy/aira) has deps:

└─ aira─0.0.0+build.12.refff15a0a (project app)
   ├─ csv─1 (git repo)
   ├─ lfe─2.0-dev (git repo)
   └─ uuid─0.0.0+build.7.ref3f79d20 (git repo)

Why when i run the command "rebar3 lfe run" an error occurs ?

===> Verifying dependencies...
===> Compiling aira
Running script '/usr/bin/rebar3' with args [] ...
exception error: undefined function
  in (uuid : v4)
  in aira:my-fun/0 (/home/prokopiy/MEGAsync/workspace/aira/src/aira.lfe, line 10)
  in lists:map/2 (lists.erl, line 1239)
  in lists:map/2 (lists.erl, line 1239)
  in lfe_eval:eval_call/2 (/home/prokopiy/MEGAsync/workspace/aira/_build/default/plugins/lfe/src/lfe_eval.erl, line 866)
  in lfescript:eval_code/4 (/home/prokopiy/MEGAsync/workspace/aira/_build/default/plugins/lfe/src/lfescript.erl, line 187)
  in lfescript:parse_check_run/3 (/home/prokopiy/MEGAsync/workspace/aira/_build/default/plugins/lfe/src/lfescript.erl, line 87)
  in lfescript:run/2 (/home/prokopiy/MEGAsync/workspace/aira/_build/default/plugins/lfe/src/lfescript.erl, line 59)

**Comment by prokopiy** [comment]
When run LFE project's main/1 function as an lfescript (rebar3 lfe run), need add path of dependencies ebin to -pa options... please fix it.

**Comment by oubiwann** [comment]
Note to self (or any contributors):

I believe adding `rebar_paths:set_paths([deps], State),` to the beginning of `run` in `rebar3_lfe_prv_run.erl` should fix this.

**Comment by prokopiy** [comment]
Everything works, thanks everyone for fixing it!
I'm use commands: "rebar3 compile", then "rebar3 lfe run"

**Comment by oubiwann** [comment]
I've not only updated this particular provider with this set-paths call, but all the other providers in rebar3_lfe. This will be merged into `release/0.3.x` shortly.
